"""Change field which dependency on Enum and add SQLEnum field

Revision ID: 6fc6d0ee30b5
Revises: d5fd1301f27a
Create Date: 2025-03-04 19:11:20.096104

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6fc6d0ee30b5"
down_revision: Union[str, None] = "d5fd1301f27a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "FILE",
        "WORD",
        "TEXT",
        name="contenttypeenum",
    ).create(op.get_bind())
    sa.Enum(
        "NOUN",
        "PRONOUN",
        "VERB",
        "ADJECTIVE",
        "ADVERB",
        "PREPOSITION",
        "CONJUNCTION",
        "INTERJECTION",
        name="partofspeachenum",
    ).create(op.get_bind())
    sa.Enum(
        "ENGLISH_US",
        "ENGLISH_BR",
        "SPANISH",
        "FRENCH",
        "GERMANY",
        name="languageenum",
    ).create(op.get_bind())
    op.execute(
        "ALTER TABLE repetitions ALTER COLUMN content_type TYPE contenttypeenum USING content_type::contenttypeenum;"
    )
    op.execute(
        "ALTER TABLE word_repetitions ALTER COLUMN part_of_speech TYPE partofspeachenum USING part_of_speech::partofspeachenum;"
    )
    op.execute(
        "ALTER TABLE word_repetitions ALTER COLUMN language TYPE languageenum USING language::languageenum;"
    )

    op.alter_column(
        "repetitions",
        "content_type",
        existing_type=sa.VARCHAR(),
        type_=postgresql.ENUM("FILE", "WORD", "TEXT", name="contenttypeenum"),
        existing_nullable=False,
    )
    op.alter_column(
        "word_repetitions",
        "part_of_speech",
        existing_type=sa.VARCHAR(length=20),
        type_=postgresql.ENUM(
            "NOUN",
            "PRONOUN",
            "VERB",
            "ADJECTIVE",
            "ADVERB",
            "PREPOSITION",
            "CONJUNCTION",
            "INTERJECTION",
            name="partofspeachenum",
        ),
        existing_nullable=True,
    )
    op.alter_column(
        "word_repetitions",
        "language",
        existing_type=sa.VARCHAR(length=30),
        type_=postgresql.ENUM(
            "ENGLISH_US",
            "ENGLISH_BR",
            "SPANISH",
            "FRENCH",
            "GERMANY",
            name="languageenum",
        ),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "word_repetitions",
        "language",
        existing_type=postgresql.ENUM(
            "ENGLISH_US",
            "ENGLISH_BR",
            "SPANISH",
            "FRENCH",
            "GERMANY",
            name="languageenum",
        ),
        type_=sa.VARCHAR(length=30),
        existing_nullable=True,
    )
    op.alter_column(
        "word_repetitions",
        "part_of_speech",
        existing_type=postgresql.ENUM(
            "NOUN",
            "PRONOUN",
            "VERB",
            "ADJECTIVE",
            "ADVERB",
            "PREPOSITION",
            "CONJUNCTION",
            "INTERJECTION",
            name="partofspeachenum",
        ),
        type_=sa.VARCHAR(length=20),
        existing_nullable=True,
    )
    op.alter_column(
        "repetitions",
        "content_type",
        existing_type=postgresql.ENUM("FILE", "WORD", "TEXT", name="contenttypeenum"),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
