"""big refactoring tables and create extra associate table for synonys

Revision ID: d5fd1301f27a
Revises: 4344e5f66ac2
Create Date: 2025-01-28 18:09:26.474160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5fd1301f27a'
down_revision: Union[str, None] = '4344e5f66ac2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slug_repetitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('word_repetitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('translate', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('part_of_speech', sa.String(length=20), nullable=True),
    sa.Column('examples', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('language', sa.String(length=30), nullable=True),
    sa.Column('context', sa.String(), nullable=True),
    sa.Column('possible_options', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word')
    )
    op.create_table('repetition_slug_association',
    sa.Column('repetition_id', sa.String(length=36), nullable=True),
    sa.Column('slug_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['repetition_id'], ['repetitions.id'], ),
    sa.ForeignKeyConstraint(['slug_id'], ['slug_repetitions.id'], )
    )
    op.create_table('synonym_association',
    sa.Column('word_id', sa.String(length=36), nullable=False),
    sa.Column('synonym_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['synonym_id'], ['word_repetitions.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['word_repetitions.id'], ),
    sa.PrimaryKeyConstraint('word_id', 'synonym_id')
    )
    op.add_column('repetitions', sa.Column('content_type', sa.String(), nullable=False))
    op.add_column('repetitions', sa.Column('content_id', sa.String(length=36), nullable=False))
    op.drop_column('repetitions', 'slug')
    op.drop_column('repetitions', 'document_link')
    op.drop_column('repetitions', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repetitions', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('repetitions', sa.Column('document_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('repetitions', sa.Column('slug', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('repetitions', 'content_id')
    op.drop_column('repetitions', 'content_type')
    op.drop_table('synonym_association')
    op.drop_table('repetition_slug_association')
    op.drop_table('word_repetitions')
    op.drop_table('slug_repetitions')
    # ### end Alembic commands ###
