"""delete associate table synonym

Revision ID: c4df710a8097
Revises: cf4bcb5be6b0
Create Date: 2025-03-23 10:33:11.572723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4df710a8097'
down_revision: Union[str, None] = 'cf4bcb5be6b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('synonym_association')
    op.add_column('word_repetitions', sa.Column('synonyms', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('word_repetitions', 'synonyms')
    op.create_table('synonym_association',
    sa.Column('word_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('synonym_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['synonym_id'], ['word_repetitions.id'], name='synonym_association_synonym_id_fkey'),
    sa.ForeignKeyConstraint(['word_id'], ['word_repetitions.id'], name='synonym_association_word_id_fkey'),
    sa.PrimaryKeyConstraint('word_id', 'synonym_id', name='synonym_association_pkey')
    )
    # ### end Alembic commands ###
