"""Add references id for word_repetition

Revision ID: b331ce708796
Revises: c4df710a8097
Create Date: 2025-11-21 01:31:16.531475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b331ce708796'
down_revision: Union[str, None] = 'c4df710a8097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_word_repetitions_repetition_id'), 'word_repetitions', type_='foreignkey')
    op.create_foreign_key(None, 'word_repetitions', 'repetitions', ['id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'word_repetitions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_word_repetitions_repetition_id'), 'word_repetitions', 'repetitions', ['id'], ['id'])
    # ### end Alembic commands ###
