"""initialization table

Revision ID: 2371eb373a65
Revises: 
Create Date: 2025-12-10 21:50:18.693446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2371eb373a65'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repetitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.Enum('BASE', 'MD', 'WORD', 'TEXT', name='repetitioncontenttypeenum'), nullable=False),
    sa.Column('count_repetition', sa.Integer(), nullable=True),
    sa.Column('date_repetition', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_last_repetition', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('slug_repetitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('repetition_slug_association',
    sa.Column('repetition_id', sa.Integer(), nullable=True),
    sa.Column('slug_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repetition_id'], ['repetitions.id'], ),
    sa.ForeignKeyConstraint(['slug_id'], ['slug_repetitions.id'], )
    )
    op.create_table('word_repetitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('translate', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('synonyms', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('part_of_speech', sa.Enum('NOUN', 'PRONOUN', 'VERB', 'ADJECTIVE', 'ADVERB', 'PREPOSITION', 'CONJUNCTION', 'INTERJECTION', name='partofspeachenum'), nullable=True),
    sa.Column('examples', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('language', sa.Enum('EN-US', 'EN_GB', 'ES', 'FR', 'DE', 'PL', name='languageenum'), nullable=True),
    sa.Column('context', sa.String(), nullable=True),
    sa.Column('possible_options', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['repetitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word_repetitions')
    op.drop_table('repetition_slug_association')
    op.drop_table('slug_repetitions')
    op.drop_table('repetitions')
    # ### end Alembic commands ###
