"""add table SlugRepetition RepetitionAggregate WordRepetition

Revision ID: b1394457fb7b
Revises: 4344e5f66ac2
Create Date: 2025-01-10 00:30:10.190524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1394457fb7b'
down_revision: Union[str, None] = '4344e5f66ac2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slug_repetitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('word_repetitions',
    sa.Column('translate', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('part_of_speech', sa.String(length=20), nullable=False),
    sa.Column('examples', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('language', sa.String(length=30), nullable=True),
    sa.Column('context', sa.String(), nullable=True),
    sa.Column('possible_options', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('count_repetition', sa.Integer(), nullable=True),
    sa.Column('date_repetition', sa.Integer(), nullable=False),
    sa.Column('date_last_repetition', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('repetition_slug_association',
    sa.Column('repetition_id', sa.String(length=36), nullable=True),
    sa.Column('slug_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['repetition_id'], ['repetitions.id'], ),
    sa.ForeignKeyConstraint(['slug_id'], ['slug_repetitions.id'], )
    )
    op.create_table('synonyms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('word_id', sa.String(length=36), nullable=False),
    sa.Column('synonym_word', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['word_id'], ['word_repetitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('repetitions', sa.Column('content_type', sa.String(), nullable=False))
    op.add_column('repetitions', sa.Column('content_id', sa.String(length=36), nullable=False))
    op.drop_constraint('repetitions_title_key', 'repetitions', type_='unique')
    op.drop_column('repetitions', 'date_last_repetition')
    op.drop_column('repetitions', 'description')
    op.drop_column('repetitions', 'date_repetition')
    op.drop_column('repetitions', 'user_id')
    op.drop_column('repetitions', 'document_link')
    op.drop_column('repetitions', 'slug')
    op.drop_column('repetitions', 'title')
    op.drop_column('repetitions', 'count_repetition')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repetitions', sa.Column('count_repetition', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('repetitions', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('repetitions', sa.Column('slug', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('repetitions', sa.Column('document_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('repetitions', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('repetitions', sa.Column('date_repetition', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('repetitions', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('repetitions', sa.Column('date_last_repetition', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_unique_constraint('repetitions_title_key', 'repetitions', ['title'])
    op.drop_column('repetitions', 'content_id')
    op.drop_column('repetitions', 'content_type')
    op.drop_table('synonyms')
    op.drop_table('repetition_slug_association')
    op.drop_table('word_repetitions')
    op.drop_table('slug_repetitions')
    # ### end Alembic commands ###
