"""Change the rules for the column polymorphic

Revision ID: cf4bcb5be6b0
Revises: 6fc6d0ee30b5
Create Date: 2025-03-14 15:33:19.931226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf4bcb5be6b0'
down_revision: Union[str, None] = '6fc6d0ee30b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repetitions', 'content_id')
    op.create_foreign_key('fk_word_repetitions_repetition_id', 'word_repetitions', 'repetitions', ['id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_word_repetitions_repetition_id', 'word_repetitions', type_='foreignkey')
    op.add_column('repetitions', sa.Column('content_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
