"""add md models

Revision ID: 33aca94c6486
Revises: 2371eb373a65
Create Date: 2026-01-26 14:57:11.960516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33aca94c6486'
down_revision: Union[str, Sequence[str], None] = '2371eb373a65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('md_repetitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('highlights', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('hints', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('load_links', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('importants', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('uniq_link', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['repetitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('md_repetitions')
    # ### end Alembic commands ###
